### ISSUE TITLE
Connection loss between name node and data node after some time

### ISSUE THREAD

**Issue by ahmibr** [SayedAlesawy/Videra-Storage#16]
## Description
- After some time, the connection between name node and data node is lost. The name node can't send any more health check messages to data node, so after it misses some messages (_which it didn't receive_) it considers it as dead.
- This bugs happens when a data node is up for some minutes (_usually 15, 20, 30_) and the problem persists even if data node was restarted.
- It gets fixed after name node is restarted.

## Expected
The connection shouldn't be lost as long as both nodes are up.

## Actual
Connection is lost after some time (_usually 15, 20, 30_).

**Comment by SayedAlesawy** [comment]
@ahmibr Does the number of online nodes or the health check frequency affect this in any way?

**Comment by SayedAlesawy** [comment]
> @ahmibr Does the number of online nodes or the health check frequency affect this in any way?

I can reproduce it on my end.

**Comment by SayedAlesawy** [comment]
I am currently suspecting that it could be a connection leak due to unclosed connections.
